# Generated by Django 4.0.6 on 2023-01-02 22:35

import Articulos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id_Artículo')),
                ('nombre', models.TextField(max_length=40)),
                ('categoria', models.CharField(choices=[('in', 'Inflable'), ('ju', 'Juego'), ('pb', 'Plaza Blanda')], default='in', max_length=2, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria'))),
                ('subcategoria', models.TextField(max_length=10, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategoria'))),
                ('stock', models.IntegerField()),
                ('precio', models.FloatField()),
                ('imagen_url', models.ImageField(blank=True, null=True, upload_to=Articulos.models.custom_upload_to)),
            ],
            options={
                'verbose_name': 'articulo',
                'verbose_name_plural': 'articulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Id_Categoría')),
                ('desc_categoria', models.TextField(max_length=15, verbose_name='Descripción Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id_subcategoria', models.TextField(max_length=10, primary_key=True, serialize=False, verbose_name='Id Subcategoría')),
                ('id_categoria', models.CharField(choices=[('in', 'Inflable'), ('ju', 'Juego'), ('pb', 'Plaza Blanda')], default='in', max_length=2, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria'))),
                ('desc_subcategoria', models.TextField(max_length=40, verbose_name='Descripción Subcategoría')),
            ],
        ),
    ]
