# Generated by Django 4.1.2 on 2023-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='subidas'),
        ),
    ]
