# Generated by Django 4.1.2 on 2023-03-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0002_alter_articulo_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen_url',
            field=models.ImageField(blank=True, null=True, upload_to='custom'),
        ),
    ]
