# Generated by Django 4.1.2 on 2022-11-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articulos', '0002_rename_articulos_articulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'verbose_name': 'articulo', 'verbose_name_plural': 'articulos'},
        ),
        migrations.AlterModelOptions(
            name='subcategoria',
            options={},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen_url',
            field=models.ImageField(upload_to='articulos'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='id_subcategoria',
            field=models.TextField(max_length=10, primary_key=True, serialize=False, verbose_name='Id Subcategoría'),
        ),
    ]
